### ISSUE TITLE
Update the documentation in readme

### ISSUE THREAD

**Issue by Glitchyi** [The-Capstone-Project/Clearch#6]

**Comment by ghost** [comment]
@Glitchyi Kindly provide details of update. Thanks.

**Comment by Glitchyi** [comment]
Clearch current repo readme out of date, also a better and more pretty update for the readme well overdue

**Comment by ghost** [comment]
Alright @Glitchyi, kindly provide details of any new additions to Clearch. Then me, @Xanthium7 and @Abinjoy025 will get to changes right away.

**Comment by Glitchyi** [comment]
General improvements to the file is the main thing, out of date references in the sense priority in the document given to older features, all features should have equal priority, also the entire readme is not organised well with full ai gen stuff

**Comment by Glitchyi** [comment]
@Xanthium7 @Abinjoy025 @iamandrewcanil  id recommend to go through the code and figure the features, ping me if anything doesnt make sense

**Comment by ghost** [comment]
Ok @Glitchyi, will get to it.

**Comment by Glitchyi** [comment]
@Xanthium7 @Abinjoy025 @iamandrewcanil It would be great if you guys split the documentation into CONTRIBUTING.md and the readme, the packaging info need not be on the main readme page

**Comment by ghost** [comment]
Yes, will complete that by today @Glitchyi

**Comment by ghost** [comment]
@Glitchyi task has been completed. Kindly inform if any changes needed.

**Comment by Glitchyi** [comment]
Ok, issue closed
